### ISSUE TITLE
You can fire as fast you can press the fire button in the archery template

### ISSUE THREAD

**Issue by HeadClot** [deprecated-armory3d/armory_templates_b27#1]
Hey @luboslenco - 

I was trying out the archery template. When I started to spam the fire button. It would spawn projectiles just as fast as I could press the fire button. I do not think there is a check in place to see if the animation is complete then fire the Arrow.

**Comment by luboslenco** [comment]
Hehe yeah no check there yet, will fix.:)

**Comment by luboslenco** [comment]
Will move this issue to the repository at https://github.com/armory3d/armory_templates, marking this one as deprecated and intended for b27 usage.
