### ISSUE TITLE
the armature

### ISSUE THREAD

**Issue by Didiercode** [deprecated-armory3d/armory_templates_b27#11]
Remark for the function init of the trait PlayerController,
at the line armature = object.getChild("Armature");

The name Armature is use 2 times in the arboresence of the player object.
If we modify one name (in the arborescence and in the  object.getChild("xxxx"); ), init repeat several times with errors.

What's happening ?

**Comment by luboslenco** [comment]
Assuming this is in regards to the twin_stick template. The armature object has a datablock named "Armature", hence the name "Armature" displayed two times in the hierarchy.

`object.getChild()` looks for an object, so when renaming it's important to rename Blender object, data block name is not relevant.
