### ISSUE TITLE
Can't run on Browser

### ISSUE THREAD

**Issue by Nodragem** [deprecated-armory3d/armory_templates_b27#12]
Hello

I just tried Armory v.05b, looks amazing! thank you for your hard work.

However when I tried to play the Twin Shooter in the Browser and I get this error message:

```
kha.js:27160 Uncaught TypeError: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': No function was found that matched the signature provided.
    at kha_WebGLImage.createTexture (kha.js:27160)
    at Function.kha_Image.fromBytes (kha.js:23785)
    at Function.armory_renderpath_RenderPathDeferred.init (kha.js:1384)
    at armory_renderpath_RenderPathCreator.get (kha.js:2420)
    at kha.js:2536
    at kha.js:1576
    at kha.js:1561
    at kha.js:2077
    at kha.js:2066
    at iron_Scene.returnObjectLoaded (kha.js:2367)
```

I tried with Chrome, Opera and Firefox.

**Comment by BlackGoku36** [comment]
Could You specify OS and which version of WebGl it use?


> I tried with Chrome, Opera and Firefox.



Does it works?

**Comment by luboslenco** [comment]
Thanks for the report, should be fixed with pull request at https://github.com/Kode/Kha/pull/898. Updated Kha will also be included in upcoming Armory builds.
