### ISSUE TITLE
Zombie game template

### ISSUE THREAD

**Issue by DevMagicLord** [deprecated-armory3d/armory_templates_b27#14]
A complete game template with minimal AI would be interesting.

Player : 
- melee weapon
- range weapon using raycast ( instead of physic projectile because no continous collision detection)
- can take damage
- each weapon has it's own logic nodes and own attributes, with an attack event trigger 

Zombies ai:
- when hit from distance , instantly see the player whatever is the distance
- hear player around (small detection radius)
- vision detection (bigger radius and angle vision combined with raycast to detect player player )
- do random attack between two, make some random small pauses between attacks
- stop pursuing player when player flee away
- Navmesh used for zombies navigation.

UI : 
- Health bar 
- Score 

Effects : 
- particles when player weapon hit zombie
- small particle effects when zombie hit player, small HUD effect when player is hit

**Comment by luboslenco** [comment]
Sounds cool but would probably be better handled as a community project.
