### ISSUE TITLE
Gun is misplaced

### ISSUE THREAD

**Issue by darkwave** [deprecated-armory3d/armory_templates_b27#5]
In first and third person templates the gun model results higher than the model holding it when running the game.

View inside Blender 2.79
![screenshot_2018-06-18_10-53-25](https://user-images.githubusercontent.com/246174/41526980-0e768c24-72e6-11e8-9682-7e6bcde4cec9.png)

View when running using Krom
![screenshot_2018-06-18_10-54-21](https://user-images.githubusercontent.com/246174/41526979-0e595960-72e6-11e8-84ae-3042a0ca9a70.png)

**Comment by luboslenco** [comment]
What armory version are you on?

If you are running armory 0.4 - download the templates from releases:
https://github.com/armory3d/armory_templates/releases

If you are running git armory (0.5) - use git version of this repository as well:
`git clone https://github.com/armory3d/armory_templates`

**Comment by aptanole** [comment]
Had the same issue when I used Armory 0.4 with the current repository templates. Downloading the release tempates from lubolenco's link solved the issue.
![third person](https://user-images.githubusercontent.com/40314968/41627501-87c14980-73ee-11e8-8a2f-1ea9d2d723fd.jpg)

**Comment by luboslenco** [comment]
Updated the readme file to make it less confusing. ☺️

**Comment by darkwave** [comment]
Perfect! That solved the issue ;-)
