### ISSUE TITLE
FPS template has gun offset vertically

### ISSUE THREAD

**Issue by thatimster** [deprecated-armory3d/armory_templates_b27#6]
It appears to be glitched
![image](https://user-images.githubusercontent.com/23441714/41815029-e62143be-77b2-11e8-803e-7123c5224f96.png)

**Comment by thatimster** [comment]
Updating SDK appeared to fix it

**Comment by luboslenco** [comment]
Updated the readme recently to make it less confusing:

> Download the package from [releases](https://github.com/armory3d/armory_templates/releases). Only use the latest revision of this repository if you are using [git Armory](http://armory3d.org/manual/#/dev/gitversion?id=armory-updater).

(As the repos are being developed simultaneously.)
