### ISSUE TITLE
Strage offset

### ISSUE THREAD

**Issue by kenthinson** [deprecated-armory3d/armory_templates_b27#7]
I'm not sure if this is a issue with the engine or with the example files. But with the third person and first person examples when I test them the gun looks fine in blender. However when in game it's not attached to the person correctly. I have not changed the file just downloaded it to look at the example.

Running on a mac. Using the 2.79b version downloaded from the Armory site.

![screen shot 2018-07-08 at 3 03 28 pm](https://user-images.githubusercontent.com/2245494/42424395-821074e4-82c0-11e8-8770-44c02a6468a6.png)
![screen shot 2018-07-08 at 3 03 53 pm](https://user-images.githubusercontent.com/2245494/42424396-822bac0a-82c0-11e8-870f-7f55e59b4772.png)

**Comment by luboslenco** [comment]
Hello,
Download the package from [releases](https://github.com/armory3d/armory_templates/releases). Only use the latest revision of this repository if you are using [git Armory](http://armory3d.org/manual/#/dev/gitversion?id=armory-updater).

**Comment by kenthinson** [comment]
Ah! working great now. Thanks! :)
