### ISSUE TITLE
The twin_sticks template fires while clicking menu items

### ISSUE THREAD

**Issue by PixelPartner** [deprecated-armory3d/armory_templates_b27#8]
It would inform me very much, when someone would add code that grabs away the clicks made in the menu UI. I suggest the formost items should be called for the clicks first and should stop further propagation like in fullblown GUIs.

**Comment by luboslenco** [comment]
Will move this issue to the repository at https://github.com/armory3d/armory_templates, marking this one as deprecated and intended for b27 usage.
