### ISSUE TITLE
Linux ( Elementary OS 5.0 ) Twin Stick Demo Linux64 crash

### ISSUE THREAD

**Issue by AndreaMonzini** [deprecated-armory3d/armory_templates_b27#9]
Hello, Twin Stick Demo works well in HTML5 ( Firefox 62 ) but it crash on native Elementary OS 5.0 Linux. I will try to test on other Distro a soon as possible.
Downloaded here:
https://armory3d.org/download.html
Hardware: Ryzen 1700 + AMD RX 580 Mesa driver.
```
linux@linux-System-Product-Name:~/Downloads/armory_demo_linux64/armory_demo$ ./game
Uniform voxelBlend not found.
Segmentation fault

```

**Comment by luboslenco** [comment]
Will move this issue to the repository at https://github.com/armory3d/armory_templates, marking this one as deprecated and intended for b27 usage.
